travis:
  secure:
    BINSTAR_TOKEN: odOvbP134whJ/IP8ksbEShPvVuL4TnqVpYS5okS/djlh+qucai3BlZR+/7b2SZCHSPMhD08J2WDZo2JOMDiZ02jRVC5vQrR8Meh7+/aondKyKc2LFJQ6qKxb4OJp/F3L/vJ3LZnf39l3I5ijNtftbdFQJ2vII5D2Hte5MwZxxYxghWhcnbAzuLHEvtFXTGhxLVlQ3vkiur7rXl1Ca1yOSbVG9pzxKyZgITf8nTG31o+7leCGpfq39eKQMt5tZj8AVp7f0/cszdfE2lPEIMK6iA+DZ+xxVQRy8KMcgaa+HrBqotLeiQ8xJGJhIF1cKEqiSJqsoRCdzutp0qNCQCIxnRvDksw1ADeiZHZ1/5bP7PLyyVQTw8wpmMTVK8ak/xwiwpAKFdpZxSYt4s+fnqJ62erOkImoLnb+tkjDdOhQzwj3Wj82wf0JuiZt49oaSdekZDF6CAwBff5c7vApq3YrrIn6sFaEKKOvhmxX190lKsNUqMSfaj3x2uLFuXEw2nIqwRZDmaRZJSRlEBlHA+1a0Q6fTxh8eQ418JMHBFzP1g5OdTRPu7jeAB6kYbj5Edtf8bl0Q/9STVEVVnNJm/1Oq2RmvGZxcfQwLIeZN+XkFWFSbesDWH2a3ISFP3zE/rGqykE8hxjG03SNiEq2Eu0CBf2Rmo+FgCvpXRhs0XQ3MKE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
